// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: provider/v1/provider.proto

package providerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProviderService_Invoke_FullMethodName          = "/provider.v1.ProviderService/Invoke"
	ProviderService_InvokeEmbedding_FullMethodName = "/provider.v1.ProviderService/InvokeEmbedding"
	ProviderService_ProviderHealth_FullMethodName  = "/provider.v1.ProviderService/ProviderHealth"
)

// ProviderServiceClient is the client API for ProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProviderServiceClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InvokeResponse], error)
	InvokeEmbedding(ctx context.Context, in *InvokeEmbeddingRequest, opts ...grpc.CallOption) (*InvokeEmbeddingResponse, error)
	ProviderHealth(ctx context.Context, in *ProviderHealthRequest, opts ...grpc.CallOption) (*ProviderHealthResponse, error)
}

type providerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderServiceClient(cc grpc.ClientConnInterface) ProviderServiceClient {
	return &providerServiceClient{cc}
}

func (c *providerServiceClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InvokeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProviderService_ServiceDesc.Streams[0], ProviderService_Invoke_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InvokeRequest, InvokeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderService_InvokeClient = grpc.ServerStreamingClient[InvokeResponse]

func (c *providerServiceClient) InvokeEmbedding(ctx context.Context, in *InvokeEmbeddingRequest, opts ...grpc.CallOption) (*InvokeEmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeEmbeddingResponse)
	err := c.cc.Invoke(ctx, ProviderService_InvokeEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ProviderHealth(ctx context.Context, in *ProviderHealthRequest, opts ...grpc.CallOption) (*ProviderHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderHealthResponse)
	err := c.cc.Invoke(ctx, ProviderService_ProviderHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServiceServer is the server API for ProviderService service.
// All implementations must embed UnimplementedProviderServiceServer
// for forward compatibility.
type ProviderServiceServer interface {
	Invoke(*InvokeRequest, grpc.ServerStreamingServer[InvokeResponse]) error
	InvokeEmbedding(context.Context, *InvokeEmbeddingRequest) (*InvokeEmbeddingResponse, error)
	ProviderHealth(context.Context, *ProviderHealthRequest) (*ProviderHealthResponse, error)
	mustEmbedUnimplementedProviderServiceServer()
}

// UnimplementedProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProviderServiceServer struct{}

func (UnimplementedProviderServiceServer) Invoke(*InvokeRequest, grpc.ServerStreamingServer[InvokeResponse]) error {
	return status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedProviderServiceServer) InvokeEmbedding(context.Context, *InvokeEmbeddingRequest) (*InvokeEmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvokeEmbedding not implemented")
}
func (UnimplementedProviderServiceServer) ProviderHealth(context.Context, *ProviderHealthRequest) (*ProviderHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProviderHealth not implemented")
}
func (UnimplementedProviderServiceServer) mustEmbedUnimplementedProviderServiceServer() {}
func (UnimplementedProviderServiceServer) testEmbeddedByValue()                         {}

// UnsafeProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServiceServer will
// result in compilation errors.
type UnsafeProviderServiceServer interface {
	mustEmbedUnimplementedProviderServiceServer()
}

func RegisterProviderServiceServer(s grpc.ServiceRegistrar, srv ProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProviderService_ServiceDesc, srv)
}

func _ProviderService_Invoke_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InvokeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProviderServiceServer).Invoke(m, &grpc.GenericServerStream[InvokeRequest, InvokeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderService_InvokeServer = grpc.ServerStreamingServer[InvokeResponse]

func _ProviderService_InvokeEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).InvokeEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_InvokeEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).InvokeEmbedding(ctx, req.(*InvokeEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ProviderHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ProviderHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ProviderHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ProviderHealth(ctx, req.(*ProviderHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProviderService_ServiceDesc is the grpc.ServiceDesc for ProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "provider.v1.ProviderService",
	HandlerType: (*ProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InvokeEmbedding",
			Handler:    _ProviderService_InvokeEmbedding_Handler,
		},
		{
			MethodName: "ProviderHealth",
			Handler:    _ProviderService_ProviderHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Invoke",
			Handler:       _ProviderService_Invoke_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "provider/v1/provider.proto",
}
