// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: provider/v1/provider.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FallbackReason int32

const (
	FallbackReason_FALLBACK_REASON_UNSPECIFIED     FallbackReason = 0
	FallbackReason_FALLBACK_REASON_BREAKER_OPEN    FallbackReason = 1
	FallbackReason_FALLBACK_REASON_QUOTA_EXHAUSTED FallbackReason = 2
)

// Enum value maps for FallbackReason.
var (
	FallbackReason_name = map[int32]string{
		0: "FALLBACK_REASON_UNSPECIFIED",
		1: "FALLBACK_REASON_BREAKER_OPEN",
		2: "FALLBACK_REASON_QUOTA_EXHAUSTED",
	}
	FallbackReason_value = map[string]int32{
		"FALLBACK_REASON_UNSPECIFIED":     0,
		"FALLBACK_REASON_BREAKER_OPEN":    1,
		"FALLBACK_REASON_QUOTA_EXHAUSTED": 2,
	}
)

func (x FallbackReason) Enum() *FallbackReason {
	p := new(FallbackReason)
	*p = x
	return p
}

func (x FallbackReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FallbackReason) Descriptor() protoreflect.EnumDescriptor {
	return file_provider_v1_provider_proto_enumTypes[0].Descriptor()
}

func (FallbackReason) Type() protoreflect.EnumType {
	return &file_provider_v1_provider_proto_enumTypes[0]
}

func (x FallbackReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FallbackReason.Descriptor instead.
func (FallbackReason) EnumDescriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{0}
}

type BreakerState int32

const (
	BreakerState_BREAKER_STATE_UNSPECIFIED BreakerState = 0
	BreakerState_BREAKER_STATE_CLOSED      BreakerState = 1
	BreakerState_BREAKER_STATE_OPEN        BreakerState = 2
	BreakerState_BREAKER_STATE_HALF_OPEN   BreakerState = 3
)

// Enum value maps for BreakerState.
var (
	BreakerState_name = map[int32]string{
		0: "BREAKER_STATE_UNSPECIFIED",
		1: "BREAKER_STATE_CLOSED",
		2: "BREAKER_STATE_OPEN",
		3: "BREAKER_STATE_HALF_OPEN",
	}
	BreakerState_value = map[string]int32{
		"BREAKER_STATE_UNSPECIFIED": 0,
		"BREAKER_STATE_CLOSED":      1,
		"BREAKER_STATE_OPEN":        2,
		"BREAKER_STATE_HALF_OPEN":   3,
	}
)

func (x BreakerState) Enum() *BreakerState {
	p := new(BreakerState)
	*p = x
	return p
}

func (x BreakerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BreakerState) Descriptor() protoreflect.EnumDescriptor {
	return file_provider_v1_provider_proto_enumTypes[1].Descriptor()
}

func (BreakerState) Type() protoreflect.EnumType {
	return &file_provider_v1_provider_proto_enumTypes[1]
}

func (x BreakerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BreakerState.Descriptor instead.
func (BreakerState) EnumDescriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{1}
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_provider_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type InvokeParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxTokens     *int32                 `protobuf:"varint,1,opt,name=max_tokens,json=maxTokens,proto3,oneof" json:"max_tokens,omitempty"`
	Temperature   *float32               `protobuf:"fixed32,2,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeParams) Reset() {
	*x = InvokeParams{}
	mi := &file_provider_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeParams) ProtoMessage() {}

func (x *InvokeParams) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeParams.ProtoReflect.Descriptor instead.
func (*InvokeParams) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeParams) GetMaxTokens() int32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

func (x *InvokeParams) GetTemperature() float32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WorkerRef     string                 `protobuf:"bytes,2,opt,name=worker_ref,json=workerRef,proto3" json:"worker_ref,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	Params        *InvokeParams          `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InvokeRequest) GetWorkerRef() string {
	if x != nil {
		return x.WorkerRef
	}
	return ""
}

func (x *InvokeRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *InvokeRequest) GetParams() *InvokeParams {
	if x != nil {
		return x.Params
	}
	return nil
}

// One item of a streamed Invoke response. Exactly one of the oneof's two
// branches is set per message: a normal content delta, or — when the
// targeted provider's breaker is open — a typed fallback signal instead of
// an error, per Phase-02.txt's INTERNAL COMMUNICATION FLOW ("Breaker open ->
// return typed 'use fallback' signal"). A typed oneof, not a gRPC status-
// code convention, so callers don't have to parse error metadata to tell
// "provider said no" apart from "breaker says don't even ask".
type InvokeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*InvokeResponse_Delta
	//	*InvokeResponse_Fallback
	Event         isInvokeResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *InvokeResponse) GetEvent() isInvokeResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *InvokeResponse) GetDelta() *Delta {
	if x != nil {
		if x, ok := x.Event.(*InvokeResponse_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

func (x *InvokeResponse) GetFallback() *FallbackSignal {
	if x != nil {
		if x, ok := x.Event.(*InvokeResponse_Fallback); ok {
			return x.Fallback
		}
	}
	return nil
}

type isInvokeResponse_Event interface {
	isInvokeResponse_Event()
}

type InvokeResponse_Delta struct {
	Delta *Delta `protobuf:"bytes,1,opt,name=delta,proto3,oneof"`
}

type InvokeResponse_Fallback struct {
	Fallback *FallbackSignal `protobuf:"bytes,2,opt,name=fallback,proto3,oneof"`
}

func (*InvokeResponse_Delta) isInvokeResponse_Event() {}

func (*InvokeResponse_Fallback) isInvokeResponse_Event() {}

type Delta struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RequestId    string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Content      *string                `protobuf:"bytes,2,opt,name=content,proto3,oneof" json:"content,omitempty"`
	FinishReason *string                `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3,oneof" json:"finish_reason,omitempty"`
	IsFinal      bool                   `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	// Provider-reported prompt-cache handle (Part P), passed through as-is.
	// Real KV reuse arrives with self-host in Phase-11 — this phase only
	// plumbs the handle from adapter response to caller.
	PrefixCacheHandle *string `protobuf:"bytes,5,opt,name=prefix_cache_handle,json=prefixCacheHandle,proto3,oneof" json:"prefix_cache_handle,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_provider_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *Delta) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Delta) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *Delta) GetFinishReason() string {
	if x != nil && x.FinishReason != nil {
		return *x.FinishReason
	}
	return ""
}

func (x *Delta) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *Delta) GetPrefixCacheHandle() string {
	if x != nil && x.PrefixCacheHandle != nil {
		return *x.PrefixCacheHandle
	}
	return ""
}

type FallbackSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Reason        FallbackReason         `protobuf:"varint,3,opt,name=reason,proto3,enum=provider.v1.FallbackReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FallbackSignal) Reset() {
	*x = FallbackSignal{}
	mi := &file_provider_v1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FallbackSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FallbackSignal) ProtoMessage() {}

func (x *FallbackSignal) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FallbackSignal.ProtoReflect.Descriptor instead.
func (*FallbackSignal) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *FallbackSignal) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FallbackSignal) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *FallbackSignal) GetReason() FallbackReason {
	if x != nil {
		return x.Reason
	}
	return FallbackReason_FALLBACK_REASON_UNSPECIFIED
}

type InvokeEmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerRef     string                 `protobuf:"bytes,1,opt,name=worker_ref,json=workerRef,proto3" json:"worker_ref,omitempty"`
	Input         []string               `protobuf:"bytes,2,rep,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeEmbeddingRequest) Reset() {
	*x = InvokeEmbeddingRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeEmbeddingRequest) ProtoMessage() {}

func (x *InvokeEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*InvokeEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *InvokeEmbeddingRequest) GetWorkerRef() string {
	if x != nil {
		return x.WorkerRef
	}
	return ""
}

func (x *InvokeEmbeddingRequest) GetInput() []string {
	if x != nil {
		return x.Input
	}
	return nil
}

type Embedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	mi := &file_provider_v1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *Embedding) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type InvokeEmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*Embedding           `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeEmbeddingResponse) Reset() {
	*x = InvokeEmbeddingResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeEmbeddingResponse) ProtoMessage() {}

func (x *InvokeEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*InvokeEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{8}
}

func (x *InvokeEmbeddingResponse) GetEmbeddings() []*Embedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

type ProviderHealthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty = report on every known provider.
	Provider      *string `protobuf:"bytes,1,opt,name=provider,proto3,oneof" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderHealthRequest) Reset() {
	*x = ProviderHealthRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderHealthRequest) ProtoMessage() {}

func (x *ProviderHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderHealthRequest.ProtoReflect.Descriptor instead.
func (*ProviderHealthRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{9}
}

func (x *ProviderHealthRequest) GetProvider() string {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return ""
}

type ProviderStatus struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Provider     string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	BreakerState BreakerState           `protobuf:"varint,2,opt,name=breaker_state,json=breakerState,proto3,enum=provider.v1.BreakerState" json:"breaker_state,omitempty"`
	// Remaining fraction of the fleet-wide quota window, [0.0, 1.0].
	QuotaHeadroom float32 `protobuf:"fixed32,3,opt,name=quota_headroom,json=quotaHeadroom,proto3" json:"quota_headroom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderStatus) Reset() {
	*x = ProviderStatus{}
	mi := &file_provider_v1_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStatus) ProtoMessage() {}

func (x *ProviderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStatus.ProtoReflect.Descriptor instead.
func (*ProviderStatus) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{10}
}

func (x *ProviderStatus) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ProviderStatus) GetBreakerState() BreakerState {
	if x != nil {
		return x.BreakerState
	}
	return BreakerState_BREAKER_STATE_UNSPECIFIED
}

func (x *ProviderStatus) GetQuotaHeadroom() float32 {
	if x != nil {
		return x.QuotaHeadroom
	}
	return 0
}

type ProviderHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*ProviderStatus      `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderHealthResponse) Reset() {
	*x = ProviderHealthResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderHealthResponse) ProtoMessage() {}

func (x *ProviderHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderHealthResponse.ProtoReflect.Descriptor instead.
func (*ProviderHealthResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{11}
}

func (x *ProviderHealthResponse) GetStatuses() []*ProviderStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

var File_provider_v1_provider_proto protoreflect.FileDescriptor

const file_provider_v1_provider_proto_rawDesc = "" +
	"\n" +
	"\x1aprovider/v1/provider.proto\x12\vprovider.v1\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"x\n" +
	"\fInvokeParams\x12\"\n" +
	"\n" +
	"max_tokens\x18\x01 \x01(\x05H\x00R\tmaxTokens\x88\x01\x01\x12%\n" +
	"\vtemperature\x18\x02 \x01(\x02H\x01R\vtemperature\x88\x01\x01B\r\n" +
	"\v_max_tokensB\x0e\n" +
	"\f_temperature\"\xb6\x01\n" +
	"\rInvokeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"worker_ref\x18\x02 \x01(\tR\tworkerRef\x124\n" +
	"\bmessages\x18\x03 \x03(\v2\x18.provider.v1.ChatMessageR\bmessages\x121\n" +
	"\x06params\x18\x04 \x01(\v2\x19.provider.v1.InvokeParamsR\x06params\"\x80\x01\n" +
	"\x0eInvokeResponse\x12*\n" +
	"\x05delta\x18\x01 \x01(\v2\x12.provider.v1.DeltaH\x00R\x05delta\x129\n" +
	"\bfallback\x18\x02 \x01(\v2\x1b.provider.v1.FallbackSignalH\x00R\bfallbackB\a\n" +
	"\x05event\"\xf5\x01\n" +
	"\x05Delta\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\acontent\x18\x02 \x01(\tH\x00R\acontent\x88\x01\x01\x12(\n" +
	"\rfinish_reason\x18\x03 \x01(\tH\x01R\ffinishReason\x88\x01\x01\x12\x19\n" +
	"\bis_final\x18\x04 \x01(\bR\aisFinal\x123\n" +
	"\x13prefix_cache_handle\x18\x05 \x01(\tH\x02R\x11prefixCacheHandle\x88\x01\x01B\n" +
	"\n" +
	"\b_contentB\x10\n" +
	"\x0e_finish_reasonB\x16\n" +
	"\x14_prefix_cache_handle\"\x80\x01\n" +
	"\x0eFallbackSignal\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x123\n" +
	"\x06reason\x18\x03 \x01(\x0e2\x1b.provider.v1.FallbackReasonR\x06reason\"M\n" +
	"\x16InvokeEmbeddingRequest\x12\x1d\n" +
	"\n" +
	"worker_ref\x18\x01 \x01(\tR\tworkerRef\x12\x14\n" +
	"\x05input\x18\x02 \x03(\tR\x05input\"#\n" +
	"\tEmbedding\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"Q\n" +
	"\x17InvokeEmbeddingResponse\x126\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x16.provider.v1.EmbeddingR\n" +
	"embeddings\"E\n" +
	"\x15ProviderHealthRequest\x12\x1f\n" +
	"\bprovider\x18\x01 \x01(\tH\x00R\bprovider\x88\x01\x01B\v\n" +
	"\t_provider\"\x93\x01\n" +
	"\x0eProviderStatus\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12>\n" +
	"\rbreaker_state\x18\x02 \x01(\x0e2\x19.provider.v1.BreakerStateR\fbreakerState\x12%\n" +
	"\x0equota_headroom\x18\x03 \x01(\x02R\rquotaHeadroom\"Q\n" +
	"\x16ProviderHealthResponse\x127\n" +
	"\bstatuses\x18\x01 \x03(\v2\x1b.provider.v1.ProviderStatusR\bstatuses*x\n" +
	"\x0eFallbackReason\x12\x1f\n" +
	"\x1bFALLBACK_REASON_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cFALLBACK_REASON_BREAKER_OPEN\x10\x01\x12#\n" +
	"\x1fFALLBACK_REASON_QUOTA_EXHAUSTED\x10\x02*|\n" +
	"\fBreakerState\x12\x1d\n" +
	"\x19BREAKER_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14BREAKER_STATE_CLOSED\x10\x01\x12\x16\n" +
	"\x12BREAKER_STATE_OPEN\x10\x02\x12\x1b\n" +
	"\x17BREAKER_STATE_HALF_OPEN\x10\x032\x8f\x02\n" +
	"\x0fProviderService\x12C\n" +
	"\x06Invoke\x12\x1a.provider.v1.InvokeRequest\x1a\x1b.provider.v1.InvokeResponse0\x01\x12\\\n" +
	"\x0fInvokeEmbedding\x12#.provider.v1.InvokeEmbeddingRequest\x1a$.provider.v1.InvokeEmbeddingResponse\x12Y\n" +
	"\x0eProviderHealth\x12\".provider.v1.ProviderHealthRequest\x1a#.provider.v1.ProviderHealthResponseBWZUgithub.com/onezox/OneZox/services/provider-gateway/internal/pb/provider/v1;providerv1b\x06proto3"

var (
	file_provider_v1_provider_proto_rawDescOnce sync.Once
	file_provider_v1_provider_proto_rawDescData []byte
)

func file_provider_v1_provider_proto_rawDescGZIP() []byte {
	file_provider_v1_provider_proto_rawDescOnce.Do(func() {
		file_provider_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_v1_provider_proto_rawDesc), len(file_provider_v1_provider_proto_rawDesc)))
	})
	return file_provider_v1_provider_proto_rawDescData
}

var file_provider_v1_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_provider_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_provider_v1_provider_proto_goTypes = []any{
	(FallbackReason)(0),             // 0: provider.v1.FallbackReason
	(BreakerState)(0),               // 1: provider.v1.BreakerState
	(*ChatMessage)(nil),             // 2: provider.v1.ChatMessage
	(*InvokeParams)(nil),            // 3: provider.v1.InvokeParams
	(*InvokeRequest)(nil),           // 4: provider.v1.InvokeRequest
	(*InvokeResponse)(nil),          // 5: provider.v1.InvokeResponse
	(*Delta)(nil),                   // 6: provider.v1.Delta
	(*FallbackSignal)(nil),          // 7: provider.v1.FallbackSignal
	(*InvokeEmbeddingRequest)(nil),  // 8: provider.v1.InvokeEmbeddingRequest
	(*Embedding)(nil),               // 9: provider.v1.Embedding
	(*InvokeEmbeddingResponse)(nil), // 10: provider.v1.InvokeEmbeddingResponse
	(*ProviderHealthRequest)(nil),   // 11: provider.v1.ProviderHealthRequest
	(*ProviderStatus)(nil),          // 12: provider.v1.ProviderStatus
	(*ProviderHealthResponse)(nil),  // 13: provider.v1.ProviderHealthResponse
}
var file_provider_v1_provider_proto_depIdxs = []int32{
	2,  // 0: provider.v1.InvokeRequest.messages:type_name -> provider.v1.ChatMessage
	3,  // 1: provider.v1.InvokeRequest.params:type_name -> provider.v1.InvokeParams
	6,  // 2: provider.v1.InvokeResponse.delta:type_name -> provider.v1.Delta
	7,  // 3: provider.v1.InvokeResponse.fallback:type_name -> provider.v1.FallbackSignal
	0,  // 4: provider.v1.FallbackSignal.reason:type_name -> provider.v1.FallbackReason
	9,  // 5: provider.v1.InvokeEmbeddingResponse.embeddings:type_name -> provider.v1.Embedding
	1,  // 6: provider.v1.ProviderStatus.breaker_state:type_name -> provider.v1.BreakerState
	12, // 7: provider.v1.ProviderHealthResponse.statuses:type_name -> provider.v1.ProviderStatus
	4,  // 8: provider.v1.ProviderService.Invoke:input_type -> provider.v1.InvokeRequest
	8,  // 9: provider.v1.ProviderService.InvokeEmbedding:input_type -> provider.v1.InvokeEmbeddingRequest
	11, // 10: provider.v1.ProviderService.ProviderHealth:input_type -> provider.v1.ProviderHealthRequest
	5,  // 11: provider.v1.ProviderService.Invoke:output_type -> provider.v1.InvokeResponse
	10, // 12: provider.v1.ProviderService.InvokeEmbedding:output_type -> provider.v1.InvokeEmbeddingResponse
	13, // 13: provider.v1.ProviderService.ProviderHealth:output_type -> provider.v1.ProviderHealthResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_provider_v1_provider_proto_init() }
func file_provider_v1_provider_proto_init() {
	if File_provider_v1_provider_proto != nil {
		return
	}
	file_provider_v1_provider_proto_msgTypes[1].OneofWrappers = []any{}
	file_provider_v1_provider_proto_msgTypes[3].OneofWrappers = []any{
		(*InvokeResponse_Delta)(nil),
		(*InvokeResponse_Fallback)(nil),
	}
	file_provider_v1_provider_proto_msgTypes[4].OneofWrappers = []any{}
	file_provider_v1_provider_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_v1_provider_proto_rawDesc), len(file_provider_v1_provider_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_v1_provider_proto_goTypes,
		DependencyIndexes: file_provider_v1_provider_proto_depIdxs,
		EnumInfos:         file_provider_v1_provider_proto_enumTypes,
		MessageInfos:      file_provider_v1_provider_proto_msgTypes,
	}.Build()
	File_provider_v1_provider_proto = out.File
	file_provider_v1_provider_proto_goTypes = nil
	file_provider_v1_provider_proto_depIdxs = nil
}
