// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: control/v1/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// spec_json carries the manifest body as a JSON-encoded string (mirrors
// model_manifest.spec_json's JSONB column, 0008_create_model_manifest.sql)
// rather than a typed message — Phase-04.txt doesn't pin down the model
// spec's own shape, and a typed proto message would force a guess at that
// shape this phase isn't chartered to make.
type RegisterModelManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelRef      string                 `protobuf:"bytes,1,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	SpecJson      string                 `protobuf:"bytes,2,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterModelManifestRequest) Reset() {
	*x = RegisterModelManifestRequest{}
	mi := &file_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModelManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModelManifestRequest) ProtoMessage() {}

func (x *RegisterModelManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModelManifestRequest.ProtoReflect.Descriptor instead.
func (*RegisterModelManifestRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterModelManifestRequest) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

func (x *RegisterModelManifestRequest) GetSpecJson() string {
	if x != nil {
		return x.SpecJson
	}
	return ""
}

func (x *RegisterModelManifestRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type RegisterModelManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionId     string                 `protobuf:"bytes,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterModelManifestResponse) Reset() {
	*x = RegisterModelManifestResponse{}
	mi := &file_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModelManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModelManifestResponse) ProtoMessage() {}

func (x *RegisterModelManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModelManifestResponse.ProtoReflect.Descriptor instead.
func (*RegisterModelManifestResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterModelManifestResponse) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

// version_id empty means "the currently active version" (resolved via
// model_active, 0009_create_model_active.sql) rather than a specific one.
type GetModelManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelRef      string                 `protobuf:"bytes,1,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	VersionId     string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelManifestRequest) Reset() {
	*x = GetModelManifestRequest{}
	mi := &file_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelManifestRequest) ProtoMessage() {}

func (x *GetModelManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelManifestRequest.ProtoReflect.Descriptor instead.
func (*GetModelManifestRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *GetModelManifestRequest) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

func (x *GetModelManifestRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

type GetModelManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionId     string                 `protobuf:"bytes,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	ModelRef      string                 `protobuf:"bytes,2,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	SpecJson      string                 `protobuf:"bytes,3,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelManifestResponse) Reset() {
	*x = GetModelManifestResponse{}
	mi := &file_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelManifestResponse) ProtoMessage() {}

func (x *GetModelManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelManifestResponse.ProtoReflect.Descriptor instead.
func (*GetModelManifestResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *GetModelManifestResponse) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *GetModelManifestResponse) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

func (x *GetModelManifestResponse) GetSpecJson() string {
	if x != nil {
		return x.SpecJson
	}
	return ""
}

func (x *GetModelManifestResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *GetModelManifestResponse) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *GetModelManifestResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetModelManifestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_control_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{4}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Models        []*ListModelsResponse_Entry `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_control_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *ListModelsResponse) GetModels() []*ListModelsResponse_Entry {
	if x != nil {
		return x.Models
	}
	return nil
}

// provider/scope select which Vault-issued credential is returned — the
// exact scoping shape (per-provider policy path, TTL) is Step J's own
// design, not fixed here beyond the request/response envelope.
type IssueProviderTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueProviderTokenRequest) Reset() {
	*x = IssueProviderTokenRequest{}
	mi := &file_control_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueProviderTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueProviderTokenRequest) ProtoMessage() {}

func (x *IssueProviderTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueProviderTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueProviderTokenRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *IssueProviderTokenRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *IssueProviderTokenRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type IssueProviderTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueProviderTokenResponse) Reset() {
	*x = IssueProviderTokenResponse{}
	mi := &file_control_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueProviderTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueProviderTokenResponse) ProtoMessage() {}

func (x *IssueProviderTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueProviderTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueProviderTokenResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *IssueProviderTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IssueProviderTokenResponse) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// strategy_json is opaque here too (mirrors RegisterModelManifestRequest's
// own spec_json reasoning) — it configures the Argo Rollouts Rollout
// resource's step list (Step M), not a field this RPC's own contract
// needs to understand. Deliberately no target-stage or percent field
// anywhere on this message: a rollout always starts at its first step.
type CreateRolloutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelRef      string                 `protobuf:"bytes,1,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	VersionId     string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	StrategyJson  string                 `protobuf:"bytes,3,opt,name=strategy_json,json=strategyJson,proto3" json:"strategy_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRolloutRequest) Reset() {
	*x = CreateRolloutRequest{}
	mi := &file_control_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRolloutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRolloutRequest) ProtoMessage() {}

func (x *CreateRolloutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRolloutRequest.ProtoReflect.Descriptor instead.
func (*CreateRolloutRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRolloutRequest) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

func (x *CreateRolloutRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *CreateRolloutRequest) GetStrategyJson() string {
	if x != nil {
		return x.StrategyJson
	}
	return ""
}

type CreateRolloutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolloutId     string                 `protobuf:"bytes,1,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRolloutResponse) Reset() {
	*x = CreateRolloutResponse{}
	mi := &file_control_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRolloutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRolloutResponse) ProtoMessage() {}

func (x *CreateRolloutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRolloutResponse.ProtoReflect.Descriptor instead.
func (*CreateRolloutResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *CreateRolloutResponse) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

// No target-stage field — advances exactly one staged step from wherever
// the rollout currently is. Same rule the internal automatic advance
// (control-plane's own Rollout-CRD watch loop, Step M) follows; this RPC
// only lets a human trigger that same one-step transition early instead
// of waiting out the current pause.
type PromoteRolloutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolloutId     string                 `protobuf:"bytes,1,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteRolloutRequest) Reset() {
	*x = PromoteRolloutRequest{}
	mi := &file_control_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteRolloutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteRolloutRequest) ProtoMessage() {}

func (x *PromoteRolloutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteRolloutRequest.ProtoReflect.Descriptor instead.
func (*PromoteRolloutRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *PromoteRolloutRequest) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

type PromoteRolloutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewStage      string                 `protobuf:"bytes,1,opt,name=new_stage,json=newStage,proto3" json:"new_stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteRolloutResponse) Reset() {
	*x = PromoteRolloutResponse{}
	mi := &file_control_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteRolloutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteRolloutResponse) ProtoMessage() {}

func (x *PromoteRolloutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteRolloutResponse.ProtoReflect.Descriptor instead.
func (*PromoteRolloutResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *PromoteRolloutResponse) GetNewStage() string {
	if x != nil {
		return x.NewStage
	}
	return ""
}

type AbortRolloutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolloutId     string                 `protobuf:"bytes,1,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRolloutRequest) Reset() {
	*x = AbortRolloutRequest{}
	mi := &file_control_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRolloutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRolloutRequest) ProtoMessage() {}

func (x *AbortRolloutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRolloutRequest.ProtoReflect.Descriptor instead.
func (*AbortRolloutRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *AbortRolloutRequest) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

type AbortRolloutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRolloutResponse) Reset() {
	*x = AbortRolloutResponse{}
	mi := &file_control_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRolloutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRolloutResponse) ProtoMessage() {}

func (x *AbortRolloutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRolloutResponse.ProtoReflect.Descriptor instead.
func (*AbortRolloutResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{13}
}

type GetRolloutStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Either identifies the rollout directly, or — if rollout_id is empty —
	// resolves model_ref's current/most recent rollout.
	RolloutId     string `protobuf:"bytes,1,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	ModelRef      string `protobuf:"bytes,2,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolloutStatusRequest) Reset() {
	*x = GetRolloutStatusRequest{}
	mi := &file_control_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolloutStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolloutStatusRequest) ProtoMessage() {}

func (x *GetRolloutStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolloutStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRolloutStatusRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *GetRolloutStatusRequest) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

func (x *GetRolloutStatusRequest) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

type GetRolloutStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolloutId     string                 `protobuf:"bytes,1,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	ModelRef      string                 `protobuf:"bytes,2,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	VersionId     string                 `protobuf:"bytes,3,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Stage         string                 `protobuf:"bytes,4,opt,name=stage,proto3" json:"stage,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CanaryPercent int32                  `protobuf:"varint,6,opt,name=canary_percent,json=canaryPercent,proto3" json:"canary_percent,omitempty"`
	StartedAt     string                 `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       string                 `protobuf:"bytes,8,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolloutStatusResponse) Reset() {
	*x = GetRolloutStatusResponse{}
	mi := &file_control_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolloutStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolloutStatusResponse) ProtoMessage() {}

func (x *GetRolloutStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolloutStatusResponse.ProtoReflect.Descriptor instead.
func (*GetRolloutStatusResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *GetRolloutStatusResponse) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

func (x *GetRolloutStatusResponse) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

func (x *GetRolloutStatusResponse) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *GetRolloutStatusResponse) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *GetRolloutStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetRolloutStatusResponse) GetCanaryPercent() int32 {
	if x != nil {
		return x.CanaryPercent
	}
	return 0
}

func (x *GetRolloutStatusResponse) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *GetRolloutStatusResponse) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

type ListModelsResponse_Entry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ModelRef        string                 `protobuf:"bytes,1,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	ActiveVersionId string                 `protobuf:"bytes,2,opt,name=active_version_id,json=activeVersionId,proto3" json:"active_version_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListModelsResponse_Entry) Reset() {
	*x = ListModelsResponse_Entry{}
	mi := &file_control_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse_Entry) ProtoMessage() {}

func (x *ListModelsResponse_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse_Entry.ProtoReflect.Descriptor instead.
func (*ListModelsResponse_Entry) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListModelsResponse_Entry) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

func (x *ListModelsResponse_Entry) GetActiveVersionId() string {
	if x != nil {
		return x.ActiveVersionId
	}
	return ""
}

var File_control_v1_control_proto protoreflect.FileDescriptor

const file_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x18control/v1/control.proto\x12\n" +
	"control.v1\"w\n" +
	"\x1cRegisterModelManifestRequest\x12\x1b\n" +
	"\tmodel_ref\x18\x01 \x01(\tR\bmodelRef\x12\x1b\n" +
	"\tspec_json\x18\x02 \x01(\tR\bspecJson\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\">\n" +
	"\x1dRegisterModelManifestResponse\x12\x1d\n" +
	"\n" +
	"version_id\x18\x01 \x01(\tR\tversionId\"U\n" +
	"\x17GetModelManifestRequest\x12\x1b\n" +
	"\tmodel_ref\x18\x01 \x01(\tR\bmodelRef\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\"\xe7\x01\n" +
	"\x18GetModelManifestResponse\x12\x1d\n" +
	"\n" +
	"version_id\x18\x01 \x01(\tR\tversionId\x12\x1b\n" +
	"\tmodel_ref\x18\x02 \x01(\tR\bmodelRef\x12\x1b\n" +
	"\tspec_json\x18\x03 \x01(\tR\bspecJson\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\x13\n" +
	"\x11ListModelsRequest\"\xa4\x01\n" +
	"\x12ListModelsResponse\x12<\n" +
	"\x06models\x18\x01 \x03(\v2$.control.v1.ListModelsResponse.EntryR\x06models\x1aP\n" +
	"\x05Entry\x12\x1b\n" +
	"\tmodel_ref\x18\x01 \x01(\tR\bmodelRef\x12*\n" +
	"\x11active_version_id\x18\x02 \x01(\tR\x0factiveVersionId\"M\n" +
	"\x19IssueProviderTokenRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\"S\n" +
	"\x1aIssueProviderTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"w\n" +
	"\x14CreateRolloutRequest\x12\x1b\n" +
	"\tmodel_ref\x18\x01 \x01(\tR\bmodelRef\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\x12#\n" +
	"\rstrategy_json\x18\x03 \x01(\tR\fstrategyJson\"6\n" +
	"\x15CreateRolloutResponse\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x01 \x01(\tR\trolloutId\"6\n" +
	"\x15PromoteRolloutRequest\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x01 \x01(\tR\trolloutId\"5\n" +
	"\x16PromoteRolloutResponse\x12\x1b\n" +
	"\tnew_stage\x18\x01 \x01(\tR\bnewStage\"4\n" +
	"\x13AbortRolloutRequest\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x01 \x01(\tR\trolloutId\"\x16\n" +
	"\x14AbortRolloutResponse\"U\n" +
	"\x17GetRolloutStatusRequest\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x01 \x01(\tR\trolloutId\x12\x1b\n" +
	"\tmodel_ref\x18\x02 \x01(\tR\bmodelRef\"\x84\x02\n" +
	"\x18GetRolloutStatusResponse\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x01 \x01(\tR\trolloutId\x12\x1b\n" +
	"\tmodel_ref\x18\x02 \x01(\tR\bmodelRef\x12\x1d\n" +
	"\n" +
	"version_id\x18\x03 \x01(\tR\tversionId\x12\x14\n" +
	"\x05stage\x18\x04 \x01(\tR\x05stage\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0ecanary_percent\x18\x06 \x01(\x05R\rcanaryPercent\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\tR\tstartedAt\x12\x19\n" +
	"\bended_at\x18\b \x01(\tR\aendedAt2\xf0\x05\n" +
	"\x0eControlService\x12l\n" +
	"\x15RegisterModelManifest\x12(.control.v1.RegisterModelManifestRequest\x1a).control.v1.RegisterModelManifestResponse\x12]\n" +
	"\x10GetModelManifest\x12#.control.v1.GetModelManifestRequest\x1a$.control.v1.GetModelManifestResponse\x12K\n" +
	"\n" +
	"ListModels\x12\x1d.control.v1.ListModelsRequest\x1a\x1e.control.v1.ListModelsResponse\x12c\n" +
	"\x12IssueProviderToken\x12%.control.v1.IssueProviderTokenRequest\x1a&.control.v1.IssueProviderTokenResponse\x12T\n" +
	"\rCreateRollout\x12 .control.v1.CreateRolloutRequest\x1a!.control.v1.CreateRolloutResponse\x12W\n" +
	"\x0ePromoteRollout\x12!.control.v1.PromoteRolloutRequest\x1a\".control.v1.PromoteRolloutResponse\x12Q\n" +
	"\fAbortRollout\x12\x1f.control.v1.AbortRolloutRequest\x1a .control.v1.AbortRolloutResponse\x12]\n" +
	"\x10GetRolloutStatus\x12#.control.v1.GetRolloutStatusRequest\x1a$.control.v1.GetRolloutStatusResponseBRZPgithub.com/onezox/OneZox/services/control-plane/internal/pb/control/v1;controlv1b\x06proto3"

var (
	file_control_v1_control_proto_rawDescOnce sync.Once
	file_control_v1_control_proto_rawDescData []byte
)

func file_control_v1_control_proto_rawDescGZIP() []byte {
	file_control_v1_control_proto_rawDescOnce.Do(func() {
		file_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_v1_control_proto_rawDesc), len(file_control_v1_control_proto_rawDesc)))
	})
	return file_control_v1_control_proto_rawDescData
}

var file_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_control_v1_control_proto_goTypes = []any{
	(*RegisterModelManifestRequest)(nil),  // 0: control.v1.RegisterModelManifestRequest
	(*RegisterModelManifestResponse)(nil), // 1: control.v1.RegisterModelManifestResponse
	(*GetModelManifestRequest)(nil),       // 2: control.v1.GetModelManifestRequest
	(*GetModelManifestResponse)(nil),      // 3: control.v1.GetModelManifestResponse
	(*ListModelsRequest)(nil),             // 4: control.v1.ListModelsRequest
	(*ListModelsResponse)(nil),            // 5: control.v1.ListModelsResponse
	(*IssueProviderTokenRequest)(nil),     // 6: control.v1.IssueProviderTokenRequest
	(*IssueProviderTokenResponse)(nil),    // 7: control.v1.IssueProviderTokenResponse
	(*CreateRolloutRequest)(nil),          // 8: control.v1.CreateRolloutRequest
	(*CreateRolloutResponse)(nil),         // 9: control.v1.CreateRolloutResponse
	(*PromoteRolloutRequest)(nil),         // 10: control.v1.PromoteRolloutRequest
	(*PromoteRolloutResponse)(nil),        // 11: control.v1.PromoteRolloutResponse
	(*AbortRolloutRequest)(nil),           // 12: control.v1.AbortRolloutRequest
	(*AbortRolloutResponse)(nil),          // 13: control.v1.AbortRolloutResponse
	(*GetRolloutStatusRequest)(nil),       // 14: control.v1.GetRolloutStatusRequest
	(*GetRolloutStatusResponse)(nil),      // 15: control.v1.GetRolloutStatusResponse
	(*ListModelsResponse_Entry)(nil),      // 16: control.v1.ListModelsResponse.Entry
}
var file_control_v1_control_proto_depIdxs = []int32{
	16, // 0: control.v1.ListModelsResponse.models:type_name -> control.v1.ListModelsResponse.Entry
	0,  // 1: control.v1.ControlService.RegisterModelManifest:input_type -> control.v1.RegisterModelManifestRequest
	2,  // 2: control.v1.ControlService.GetModelManifest:input_type -> control.v1.GetModelManifestRequest
	4,  // 3: control.v1.ControlService.ListModels:input_type -> control.v1.ListModelsRequest
	6,  // 4: control.v1.ControlService.IssueProviderToken:input_type -> control.v1.IssueProviderTokenRequest
	8,  // 5: control.v1.ControlService.CreateRollout:input_type -> control.v1.CreateRolloutRequest
	10, // 6: control.v1.ControlService.PromoteRollout:input_type -> control.v1.PromoteRolloutRequest
	12, // 7: control.v1.ControlService.AbortRollout:input_type -> control.v1.AbortRolloutRequest
	14, // 8: control.v1.ControlService.GetRolloutStatus:input_type -> control.v1.GetRolloutStatusRequest
	1,  // 9: control.v1.ControlService.RegisterModelManifest:output_type -> control.v1.RegisterModelManifestResponse
	3,  // 10: control.v1.ControlService.GetModelManifest:output_type -> control.v1.GetModelManifestResponse
	5,  // 11: control.v1.ControlService.ListModels:output_type -> control.v1.ListModelsResponse
	7,  // 12: control.v1.ControlService.IssueProviderToken:output_type -> control.v1.IssueProviderTokenResponse
	9,  // 13: control.v1.ControlService.CreateRollout:output_type -> control.v1.CreateRolloutResponse
	11, // 14: control.v1.ControlService.PromoteRollout:output_type -> control.v1.PromoteRolloutResponse
	13, // 15: control.v1.ControlService.AbortRollout:output_type -> control.v1.AbortRolloutResponse
	15, // 16: control.v1.ControlService.GetRolloutStatus:output_type -> control.v1.GetRolloutStatusResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_control_v1_control_proto_init() }
func file_control_v1_control_proto_init() {
	if File_control_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_v1_control_proto_rawDesc), len(file_control_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_v1_control_proto_goTypes,
		DependencyIndexes: file_control_v1_control_proto_depIdxs,
		MessageInfos:      file_control_v1_control_proto_msgTypes,
	}.Build()
	File_control_v1_control_proto = out.File
	file_control_v1_control_proto_goTypes = nil
	file_control_v1_control_proto_depIdxs = nil
}
