#!/usr/bin/env bash
# Regenerates services/control-plane/internal/pb/ from proto/control/v1.
# Same reasoning as provider-gateway's own generate_proto.sh: this
# service's Docker build context is scoped to services/control-plane/ and
# can't reach proto/ at the repo root, so generated code is committed here
# and regenerated by this script when control.proto changes, not produced
# by buf's remote codegen plugins at build time.
#
# Prerequisite:
#   go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
#   go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
# (both must be on $PATH, e.g. via $(go env GOPATH)/bin)

set -euo pipefail

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"  # repo root

OUT_DIR=services/control-plane/internal/pb
mkdir -p "$OUT_DIR"

protoc \
  -I proto \
  --go_out="$OUT_DIR" --go_opt=paths=source_relative \
  --go-grpc_out="$OUT_DIR" --go-grpc_opt=paths=source_relative \
  proto/control/v1/control.proto

echo "Regenerated $OUT_DIR/"
