#!/usr/bin/env bash
# Regenerates services/data-plane/generated/ from proto/gateway/v1,
# proto/dataplane/v1, and proto/provider/v1.
#
# Generated with grpcio-tools' own protoc (no network/BSR dependency), not
# buf's remote codegen plugins: the Docker build context for this service is
# scoped to services/data-plane/ (matching every other service's
# Dockerfile), so proto/ isn't reachable from inside that build — generated
# code is committed here instead and regenerated by this script when the
# .proto sources change. Same pattern dataplane-stub's own
# generate_proto.sh established in Phase-00.
#
# proto/provider/v1 is included (not just proto/dataplane/v1) because
# Phase-03 Step B wires a real gRPC client to provider-gateway (calls
# ProviderHealth on boot, proving connectivity the same way the Phase-00
# stubs proved Cockroach/Redis) — Steps D/E's real Invoke() dispatch reuses
# these same generated stubs, not a second codegen pass.
#
# protobuf's Python runtime enforces a minimum generator/runtime version
# match. requirements.txt pins protobuf==5.29.6 and grpcio to match
# grpcio-tools==1.71.0 used here — same version pin dataplane-stub's own
# script documents (chosen so opentelemetry-proto==1.38.0's protobuf<6.0 cap
# isn't violated). Regenerating with a different grpcio-tools requires
# re-checking this constraint, not just re-pinning to whatever it resolves.
#
# Prerequisite: pip install "grpcio-tools==1.71.0" in whatever environment
# runs this script.
set -euo pipefail

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"  # repo root

mkdir -p services/data-plane/generated

python3 -m grpc_tools.protoc \
  -I proto \
  --python_out=services/data-plane/generated \
  --grpc_python_out=services/data-plane/generated \
  --pyi_out=services/data-plane/generated \
  proto/gateway/v1/gateway.proto \
  proto/dataplane/v1/dataplane.proto \
  proto/provider/v1/provider.proto

find services/data-plane/generated -type d -exec touch {}/__init__.py \;

echo "Regenerated services/data-plane/generated/"
