#!/usr/bin/env bash
# Regenerates services/provider-gateway/internal/pb/ from proto/provider/v1.
#
# Generated with a local protoc + protoc-gen-go/protoc-gen-go-grpc (no
# network/BSR dependency), not buf's remote codegen plugins: the Docker
# build context for this service is scoped to services/provider-gateway/
# (matching the other two services' Dockerfiles and CI's existing
# `docker build ... services/${matrix.service}` pattern), so proto/ isn't
# reachable from inside that build — generated code is committed here
# instead and regenerated by this script when provider.proto changes. Same
# reasoning as dataplane-stub's generate_proto.sh and edge-gateway's
# #[ignore] regenerate_proto test.
#
# Prerequisite:
#   go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
#   go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
# (both must be on $PATH, e.g. via $(go env GOPATH)/bin)

set -euo pipefail

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"  # repo root

OUT_DIR=services/provider-gateway/internal/pb
mkdir -p "$OUT_DIR"

protoc \
  -I proto \
  --go_out="$OUT_DIR" --go_opt=paths=source_relative \
  --go-grpc_out="$OUT_DIR" --go-grpc_opt=paths=source_relative \
  proto/provider/v1/provider.proto

echo "Regenerated $OUT_DIR/"
