// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: control/v1/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// spec_json carries the manifest body as a JSON-encoded string (mirrors
// model_manifest.spec_json's JSONB column, 0008_create_model_manifest.sql)
// rather than a typed message — Phase-04.txt doesn't pin down the model
// spec's own shape, and a typed proto message would force a guess at that
// shape this phase isn't chartered to make.
type RegisterModelManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelRef      string                 `protobuf:"bytes,1,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	SpecJson      string                 `protobuf:"bytes,2,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterModelManifestRequest) Reset() {
	*x = RegisterModelManifestRequest{}
	mi := &file_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModelManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModelManifestRequest) ProtoMessage() {}

func (x *RegisterModelManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModelManifestRequest.ProtoReflect.Descriptor instead.
func (*RegisterModelManifestRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterModelManifestRequest) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

func (x *RegisterModelManifestRequest) GetSpecJson() string {
	if x != nil {
		return x.SpecJson
	}
	return ""
}

func (x *RegisterModelManifestRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type RegisterModelManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionId     string                 `protobuf:"bytes,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterModelManifestResponse) Reset() {
	*x = RegisterModelManifestResponse{}
	mi := &file_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModelManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModelManifestResponse) ProtoMessage() {}

func (x *RegisterModelManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModelManifestResponse.ProtoReflect.Descriptor instead.
func (*RegisterModelManifestResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterModelManifestResponse) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

// version_id empty means "the currently active version" (resolved via
// model_active, 0009_create_model_active.sql) rather than a specific one.
type GetModelManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelRef      string                 `protobuf:"bytes,1,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	VersionId     string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelManifestRequest) Reset() {
	*x = GetModelManifestRequest{}
	mi := &file_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelManifestRequest) ProtoMessage() {}

func (x *GetModelManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelManifestRequest.ProtoReflect.Descriptor instead.
func (*GetModelManifestRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *GetModelManifestRequest) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

func (x *GetModelManifestRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

type GetModelManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionId     string                 `protobuf:"bytes,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	ModelRef      string                 `protobuf:"bytes,2,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	SpecJson      string                 `protobuf:"bytes,3,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelManifestResponse) Reset() {
	*x = GetModelManifestResponse{}
	mi := &file_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelManifestResponse) ProtoMessage() {}

func (x *GetModelManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelManifestResponse.ProtoReflect.Descriptor instead.
func (*GetModelManifestResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *GetModelManifestResponse) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *GetModelManifestResponse) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

func (x *GetModelManifestResponse) GetSpecJson() string {
	if x != nil {
		return x.SpecJson
	}
	return ""
}

func (x *GetModelManifestResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *GetModelManifestResponse) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *GetModelManifestResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetModelManifestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_control_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{4}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Models        []*ListModelsResponse_Entry `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_control_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *ListModelsResponse) GetModels() []*ListModelsResponse_Entry {
	if x != nil {
		return x.Models
	}
	return nil
}

// provider/scope select which Vault-issued credential is returned — the
// exact scoping shape (per-provider policy path, TTL) is Step J's own
// design, not fixed here beyond the request/response envelope.
type IssueProviderTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueProviderTokenRequest) Reset() {
	*x = IssueProviderTokenRequest{}
	mi := &file_control_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueProviderTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueProviderTokenRequest) ProtoMessage() {}

func (x *IssueProviderTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueProviderTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueProviderTokenRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *IssueProviderTokenRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *IssueProviderTokenRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type IssueProviderTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueProviderTokenResponse) Reset() {
	*x = IssueProviderTokenResponse{}
	mi := &file_control_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueProviderTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueProviderTokenResponse) ProtoMessage() {}

func (x *IssueProviderTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueProviderTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueProviderTokenResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *IssueProviderTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IssueProviderTokenResponse) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type ListModelsResponse_Entry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ModelRef        string                 `protobuf:"bytes,1,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	ActiveVersionId string                 `protobuf:"bytes,2,opt,name=active_version_id,json=activeVersionId,proto3" json:"active_version_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListModelsResponse_Entry) Reset() {
	*x = ListModelsResponse_Entry{}
	mi := &file_control_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse_Entry) ProtoMessage() {}

func (x *ListModelsResponse_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse_Entry.ProtoReflect.Descriptor instead.
func (*ListModelsResponse_Entry) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListModelsResponse_Entry) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

func (x *ListModelsResponse_Entry) GetActiveVersionId() string {
	if x != nil {
		return x.ActiveVersionId
	}
	return ""
}

var File_control_v1_control_proto protoreflect.FileDescriptor

const file_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x18control/v1/control.proto\x12\n" +
	"control.v1\"w\n" +
	"\x1cRegisterModelManifestRequest\x12\x1b\n" +
	"\tmodel_ref\x18\x01 \x01(\tR\bmodelRef\x12\x1b\n" +
	"\tspec_json\x18\x02 \x01(\tR\bspecJson\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\">\n" +
	"\x1dRegisterModelManifestResponse\x12\x1d\n" +
	"\n" +
	"version_id\x18\x01 \x01(\tR\tversionId\"U\n" +
	"\x17GetModelManifestRequest\x12\x1b\n" +
	"\tmodel_ref\x18\x01 \x01(\tR\bmodelRef\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\"\xe7\x01\n" +
	"\x18GetModelManifestResponse\x12\x1d\n" +
	"\n" +
	"version_id\x18\x01 \x01(\tR\tversionId\x12\x1b\n" +
	"\tmodel_ref\x18\x02 \x01(\tR\bmodelRef\x12\x1b\n" +
	"\tspec_json\x18\x03 \x01(\tR\bspecJson\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\x13\n" +
	"\x11ListModelsRequest\"\xa4\x01\n" +
	"\x12ListModelsResponse\x12<\n" +
	"\x06models\x18\x01 \x03(\v2$.control.v1.ListModelsResponse.EntryR\x06models\x1aP\n" +
	"\x05Entry\x12\x1b\n" +
	"\tmodel_ref\x18\x01 \x01(\tR\bmodelRef\x12*\n" +
	"\x11active_version_id\x18\x02 \x01(\tR\x0factiveVersionId\"M\n" +
	"\x19IssueProviderTokenRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\"S\n" +
	"\x1aIssueProviderTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds2\x8f\x03\n" +
	"\x0eControlService\x12l\n" +
	"\x15RegisterModelManifest\x12(.control.v1.RegisterModelManifestRequest\x1a).control.v1.RegisterModelManifestResponse\x12]\n" +
	"\x10GetModelManifest\x12#.control.v1.GetModelManifestRequest\x1a$.control.v1.GetModelManifestResponse\x12K\n" +
	"\n" +
	"ListModels\x12\x1d.control.v1.ListModelsRequest\x1a\x1e.control.v1.ListModelsResponse\x12c\n" +
	"\x12IssueProviderToken\x12%.control.v1.IssueProviderTokenRequest\x1a&.control.v1.IssueProviderTokenResponseBRZPgithub.com/onezox/OneZox/services/control-plane/internal/pb/control/v1;controlv1b\x06proto3"

var (
	file_control_v1_control_proto_rawDescOnce sync.Once
	file_control_v1_control_proto_rawDescData []byte
)

func file_control_v1_control_proto_rawDescGZIP() []byte {
	file_control_v1_control_proto_rawDescOnce.Do(func() {
		file_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_v1_control_proto_rawDesc), len(file_control_v1_control_proto_rawDesc)))
	})
	return file_control_v1_control_proto_rawDescData
}

var file_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_control_v1_control_proto_goTypes = []any{
	(*RegisterModelManifestRequest)(nil),  // 0: control.v1.RegisterModelManifestRequest
	(*RegisterModelManifestResponse)(nil), // 1: control.v1.RegisterModelManifestResponse
	(*GetModelManifestRequest)(nil),       // 2: control.v1.GetModelManifestRequest
	(*GetModelManifestResponse)(nil),      // 3: control.v1.GetModelManifestResponse
	(*ListModelsRequest)(nil),             // 4: control.v1.ListModelsRequest
	(*ListModelsResponse)(nil),            // 5: control.v1.ListModelsResponse
	(*IssueProviderTokenRequest)(nil),     // 6: control.v1.IssueProviderTokenRequest
	(*IssueProviderTokenResponse)(nil),    // 7: control.v1.IssueProviderTokenResponse
	(*ListModelsResponse_Entry)(nil),      // 8: control.v1.ListModelsResponse.Entry
}
var file_control_v1_control_proto_depIdxs = []int32{
	8, // 0: control.v1.ListModelsResponse.models:type_name -> control.v1.ListModelsResponse.Entry
	0, // 1: control.v1.ControlService.RegisterModelManifest:input_type -> control.v1.RegisterModelManifestRequest
	2, // 2: control.v1.ControlService.GetModelManifest:input_type -> control.v1.GetModelManifestRequest
	4, // 3: control.v1.ControlService.ListModels:input_type -> control.v1.ListModelsRequest
	6, // 4: control.v1.ControlService.IssueProviderToken:input_type -> control.v1.IssueProviderTokenRequest
	1, // 5: control.v1.ControlService.RegisterModelManifest:output_type -> control.v1.RegisterModelManifestResponse
	3, // 6: control.v1.ControlService.GetModelManifest:output_type -> control.v1.GetModelManifestResponse
	5, // 7: control.v1.ControlService.ListModels:output_type -> control.v1.ListModelsResponse
	7, // 8: control.v1.ControlService.IssueProviderToken:output_type -> control.v1.IssueProviderTokenResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_control_v1_control_proto_init() }
func file_control_v1_control_proto_init() {
	if File_control_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_v1_control_proto_rawDesc), len(file_control_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_v1_control_proto_goTypes,
		DependencyIndexes: file_control_v1_control_proto_depIdxs,
		MessageInfos:      file_control_v1_control_proto_msgTypes,
	}.Build()
	File_control_v1_control_proto = out.File
	file_control_v1_control_proto_goTypes = nil
	file_control_v1_control_proto_depIdxs = nil
}
