// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type AdminUser struct {
	ID    string `json:"id"`
	OrgID string `json:"orgId"`
	Role  string `json:"role"`
}

// Never exposes hash or raw key — raw_key is returned exactly once, by the createApiKey gRPC command's own response, never by a query.
type APIKeySummary struct {
	KeyID     string   `json:"keyId"`
	OrgID     string   `json:"orgId"`
	Scopes    []string `json:"scopes"`
	CreatedAt string   `json:"createdAt"`
	RevokedAt *string  `json:"revokedAt,omitempty"`
}

type AuditEntry struct {
	AuditID    string  `json:"auditId"`
	Actor      string  `json:"actor"`
	Action     string  `json:"action"`
	Target     string  `json:"target"`
	BeforeJSON *string `json:"beforeJson,omitempty"`
	AfterJSON  *string `json:"afterJson,omitempty"`
	Ts         string  `json:"ts"`
}

type DashboardMetrics struct {
	RequestsPerSecond   float64 `json:"requestsPerSecond"`
	P95LatencyMs        float64 `json:"p95LatencyMs"`
	ErrorRate           float64 `json:"errorRate"`
	ActiveModelsCount   int     `json:"activeModelsCount"`
	ActiveRolloutsCount int     `json:"activeRolloutsCount"`
}

type ModelManifest struct {
	VersionID string `json:"versionId"`
	ModelRef  string `json:"modelRef"`
	SpecJSON  string `json:"specJson"`
	Signature string `json:"signature"`
	CreatedBy string `json:"createdBy"`
	CreatedAt string `json:"createdAt"`
	Status    string `json:"status"`
}

type ModelSummary struct {
	ModelRef        string `json:"modelRef"`
	ActiveVersionID string `json:"activeVersionId"`
}

type ProviderHealth struct {
	Provider      string  `json:"provider"`
	Healthy       bool    `json:"healthy"`
	QuotaHeadroom float64 `json:"quotaHeadroom"`
	BreakerState  string  `json:"breakerState"`
}

type Query struct {
}

type Rollout struct {
	RolloutID     string  `json:"rolloutId"`
	ModelRef      string  `json:"modelRef"`
	VersionID     string  `json:"versionId"`
	StrategyJSON  string  `json:"strategyJson"`
	Stage         string  `json:"stage"`
	Status        string  `json:"status"`
	CanaryPercent int     `json:"canaryPercent"`
	StartedAt     string  `json:"startedAt"`
	EndedAt       *string `json:"endedAt,omitempty"`
}
