// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChatMessage {
    #[prost(string, tag = "1")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatCompletionRequest {
    #[prost(string, tag = "1")]
    pub model: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<ChatMessage>,
    #[prost(bool, tag = "3")]
    pub stream: bool,
    #[prost(int32, optional, tag = "4")]
    pub max_tokens: ::core::option::Option<i32>,
    #[prost(float, optional, tag = "5")]
    pub temperature: ::core::option::Option<f32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChatCompletionChoice {
    #[prost(int32, tag = "1")]
    pub index: i32,
    #[prost(message, optional, tag = "2")]
    pub message: ::core::option::Option<ChatMessage>,
    #[prost(string, optional, tag = "3")]
    pub finish_reason: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatCompletionResponse {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub model: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub choices: ::prost::alloc::vec::Vec<ChatCompletionChoice>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChatCompletionChunkDelta {
    #[prost(string, optional, tag = "1")]
    pub role: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub content: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChatCompletionChunkChoice {
    #[prost(int32, tag = "1")]
    pub index: i32,
    #[prost(message, optional, tag = "2")]
    pub delta: ::core::option::Option<ChatCompletionChunkDelta>,
    #[prost(string, optional, tag = "3")]
    pub finish_reason: ::core::option::Option<::prost::alloc::string::String>,
}
/// Wire shape of each SSE "data:" payload when stream = true.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatCompletionChunk {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub model: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub choices: ::prost::alloc::vec::Vec<ChatCompletionChunkChoice>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResponsesRequest {
    #[prost(string, tag = "1")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub input: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub stream: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResponsesResponse {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub output_text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EmbeddingsRequest {
    #[prost(string, tag = "1")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub input: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Embedding {
    #[prost(int32, tag = "1")]
    pub index: i32,
    #[prost(float, repeated, tag = "2")]
    pub values: ::prost::alloc::vec::Vec<f32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmbeddingsResponse {
    #[prost(string, tag = "1")]
    pub model: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub data: ::prost::alloc::vec::Vec<Embedding>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Model {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub owned_by: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelsListResponse {
    #[prost(message, repeated, tag = "1")]
    pub data: ::prost::alloc::vec::Vec<Model>,
}
