#!/usr/bin/env bash
# Regenerates services/dataplane-stub/generated/ from proto/gateway/v1 and
# proto/dataplane/v1.
#
# Generated with grpcio-tools' own protoc (no network/BSR dependency), not
# buf's remote codegen plugins: the Docker build context for this service is
# scoped to services/dataplane-stub/ (see .github/workflows/ci.yml), so
# proto/ isn't reachable from inside that build — generated code is
# committed here instead and regenerated by this script when the .proto
# sources change.
#
# protobuf's Python runtime enforces a minimum generator/runtime version
# match (see the "NO CHECKED-IN PROTOBUF GENCODE" warning emitted into every
# generated _pb2.py). requirements.txt pins protobuf==5.29.6 and grpcio to
# match grpcio-tools==1.71.0 used here — this specific older grpcio-tools
# was chosen because it generates against protobuf<6.0, which is what
# opentelemetry-proto==1.38.0 (Phase-00 pin) caps the runtime to; grpcio-tools
# latest (1.83.0) generates protobuf==7.35.1-only code and conflicts with
# that OTel pin. Regenerating with a different grpcio-tools requires
# re-checking this constraint, not just re-pinning to whatever it resolves.
#
# Prerequisite: pip install "grpcio-tools==1.71.0" in whatever environment
# runs this script.
set -euo pipefail

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"  # repo root

mkdir -p services/dataplane-stub/generated

python3 -m grpc_tools.protoc \
  -I proto \
  --python_out=services/dataplane-stub/generated \
  --grpc_python_out=services/dataplane-stub/generated \
  --pyi_out=services/dataplane-stub/generated \
  proto/gateway/v1/gateway.proto \
  proto/dataplane/v1/dataplane.proto

find services/dataplane-stub/generated -type d -exec touch {}/__init__.py \;

echo "Regenerated services/dataplane-stub/generated/"
