#!/usr/bin/env bash
# Regenerates services/admin-api/internal/pb/ from proto/admin/v1 (this
# service's own gRPC server contract) and proto/control/v1 (admin-api is
# also a gRPC CLIENT of control-plane — CreateRollout/PromoteRollout/
# AbortRollout/GetRolloutStatus, Steps L/H onward — needs its own copy of
# control.proto's generated stubs, same reasoning as provider-gateway's
# own generate_proto.sh already established for IssueProviderToken).
#
# Local protoc + protoc-gen-go/protoc-gen-go-grpc, not buf's remote
# codegen plugins: this service's Docker build context is scoped to
# services/admin-api/ and can't reach proto/ at the repo root — generated
# code is committed here and regenerated by this script when either
# .proto changes, the same convention every other Go/Rust service in this
# project already uses.
#
# Prerequisite:
#   go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
#   go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
# (both must be on $PATH, e.g. via $(go env GOPATH)/bin)

set -euo pipefail

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"  # repo root

OUT_DIR=services/admin-api/internal/pb
mkdir -p "$OUT_DIR"

protoc \
  -I proto \
  --go_out="$OUT_DIR" --go_opt=paths=source_relative \
  --go-grpc_out="$OUT_DIR" --go-grpc_opt=paths=source_relative \
  proto/admin/v1/admin.proto

# Only the client-side generated code (ControlServiceClient) is actually
# used; protoc-gen-go-grpc generates the server interface alongside it
# regardless, unused here, harmless — same note provider-gateway's own
# script already makes for this exact situation.
protoc \
  -I proto \
  --go_out="$OUT_DIR" --go_opt=paths=source_relative \
  --go-grpc_out="$OUT_DIR" --go-grpc_opt=paths=source_relative \
  proto/control/v1/control.proto

# Step U1b: admin-api is also a gRPC client of provider-gateway, for
# ProviderHealth ONLY (the panel's Provider Console, Part R — breaker
# state + quota headroom). Same client-side-only note as control.proto
# above; Invoke/InvokeEmbedding are generated but never called from here
# (admin-api's own narrow providerHealthReader interface is what makes
# that structural rather than a matter of discipline).
protoc \
  -I proto \
  --go_out="$OUT_DIR" --go_opt=paths=source_relative \
  --go-grpc_out="$OUT_DIR" --go-grpc_opt=paths=source_relative \
  proto/provider/v1/provider.proto

echo "Regenerated $OUT_DIR/"
