// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: admin/v1/admin.proto

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_PublishModelVersion_FullMethodName = "/admin.v1.AdminService/PublishModelVersion"
	AdminService_StartRollout_FullMethodName        = "/admin.v1.AdminService/StartRollout"
	AdminService_PromoteRollout_FullMethodName      = "/admin.v1.AdminService/PromoteRollout"
	AdminService_AbortRollout_FullMethodName        = "/admin.v1.AdminService/AbortRollout"
	AdminService_CreateApiKey_FullMethodName        = "/admin.v1.AdminService/CreateApiKey"
	AdminService_RevokeApiKey_FullMethodName        = "/admin.v1.AdminService/RevokeApiKey"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Phase-05's admin-api contract (Architecture Part R). This is the panel's
// COMMAND surface only — every RPC here is a mutation with a real side
// effect and a corresponding audit_log row. Reads (dashboard, model list,
// rollout status, audit history, key list) are GraphQL instead (see
// proto/admin/v1/admin.graphql) — the deliberate split: GraphQL's flexible
// field-selection suits Next.js RSC's varying per-page read shapes, while
// every mutation here is a single fixed command better served by a typed
// RPC with no shape ambiguity, matching every other command-style RPC in
// this project (e.g. dataplane.v1.Submit).
//
// Every RPC requires an authenticated admin_user, carried as gRPC metadata
// ("authorization: bearer <admin-token>"), not a message field — the same
// separation Vault's own Kubernetes-auth login uses (identity is a
// transport-level concern, never something a request message carries and
// a caller could spoof). RBAC (viewer vs admin, Step G) is enforced
// per-RPC server-side before any handler body runs.
//
// EC4 is enforced by this file's own shape, not just by server-side
// checks: there is no RPC here that sets model_active directly, no
// "instant activate" verb, and no field on StartRollout/PromoteRollout
// that accepts a target stage or percentage. PromoteRollout advances
// EXACTLY one staged step (skipping only the current pause), the same
// single-step rule the automatic timer-driven advance uses internally —
// it cannot jump ahead. If a bypass verb isn't in this file, no caller,
// however privileged, can invoke one.
//
// createModelDraft (Phase-05.txt's own APIS CREATED wording) is
// deliberately NOT an RPC here: it never mutates anything (it reads the
// currently active manifest as the Model Studio editor's starting point),
// so it is the GraphQL query `modelDraft` instead — Phase-05.txt's own
// "createModelDraft/publishModelVersion -> control-plane
// RegisterModelManifest" line groups the two adjacent UX steps together,
// but only publish should ever produce a new signed version; a draft that
// silently persisted a manifest would defeat the whole point of staging
// an edit before committing it.
type AdminServiceClient interface {
	// -> control.v1.ControlService/RegisterModelManifest (unchanged, P04).
	// created_by is never a request field — derived server-side from the
	// authenticated caller (Step F), so a client can never attribute a
	// publish to someone else.
	PublishModelVersion(ctx context.Context, in *PublishModelVersionRequest, opts ...grpc.CallOption) (*PublishModelVersionResponse, error)
	// -> control.v1.ControlService/CreateRollout (new this phase). Always
	// begins at the first staged step; there is no field to start
	// elsewhere or at a given percentage.
	StartRollout(ctx context.Context, in *StartRolloutRequest, opts ...grpc.CallOption) (*StartRolloutResponse, error)
	// -> control.v1.ControlService/PromoteRollout. Manual "don't wait out
	// the pause" control (Architecture Part R: "live promote/rollback
	// controls") — advances exactly one step, identical in effect to the
	// automatic timer-driven advance, just human-triggered.
	PromoteRollout(ctx context.Context, in *PromoteRolloutRequest, opts ...grpc.CallOption) (*PromoteRolloutResponse, error)
	// -> control.v1.ControlService/AbortRollout. Manual rollback — zeroes
	// canary traffic, identical in effect to an automatic AnalysisRun-
	// triggered rollback, just human-triggered.
	AbortRollout(ctx context.Context, in *AbortRolloutRequest, opts ...grpc.CallOption) (*AbortRolloutResponse, error)
	// Local to admin-api's own api_keys grant (P01's table, reused) — does
	// not reach control-plane at all. raw_key is returned exactly once and
	// never persisted (mirrors data/seed/seed-test-tenant.sh's own
	// discipline); only its hash is stored.
	CreateApiKey(ctx context.Context, in *CreateApiKeyRequest, opts ...grpc.CallOption) (*CreateApiKeyResponse, error)
	RevokeApiKey(ctx context.Context, in *RevokeApiKeyRequest, opts ...grpc.CallOption) (*RevokeApiKeyResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) PublishModelVersion(ctx context.Context, in *PublishModelVersionRequest, opts ...grpc.CallOption) (*PublishModelVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishModelVersionResponse)
	err := c.cc.Invoke(ctx, AdminService_PublishModelVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) StartRollout(ctx context.Context, in *StartRolloutRequest, opts ...grpc.CallOption) (*StartRolloutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRolloutResponse)
	err := c.cc.Invoke(ctx, AdminService_StartRollout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) PromoteRollout(ctx context.Context, in *PromoteRolloutRequest, opts ...grpc.CallOption) (*PromoteRolloutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromoteRolloutResponse)
	err := c.cc.Invoke(ctx, AdminService_PromoteRollout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AbortRollout(ctx context.Context, in *AbortRolloutRequest, opts ...grpc.CallOption) (*AbortRolloutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortRolloutResponse)
	err := c.cc.Invoke(ctx, AdminService_AbortRollout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateApiKey(ctx context.Context, in *CreateApiKeyRequest, opts ...grpc.CallOption) (*CreateApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateApiKeyResponse)
	err := c.cc.Invoke(ctx, AdminService_CreateApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RevokeApiKey(ctx context.Context, in *RevokeApiKeyRequest, opts ...grpc.CallOption) (*RevokeApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeApiKeyResponse)
	err := c.cc.Invoke(ctx, AdminService_RevokeApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// Phase-05's admin-api contract (Architecture Part R). This is the panel's
// COMMAND surface only — every RPC here is a mutation with a real side
// effect and a corresponding audit_log row. Reads (dashboard, model list,
// rollout status, audit history, key list) are GraphQL instead (see
// proto/admin/v1/admin.graphql) — the deliberate split: GraphQL's flexible
// field-selection suits Next.js RSC's varying per-page read shapes, while
// every mutation here is a single fixed command better served by a typed
// RPC with no shape ambiguity, matching every other command-style RPC in
// this project (e.g. dataplane.v1.Submit).
//
// Every RPC requires an authenticated admin_user, carried as gRPC metadata
// ("authorization: bearer <admin-token>"), not a message field — the same
// separation Vault's own Kubernetes-auth login uses (identity is a
// transport-level concern, never something a request message carries and
// a caller could spoof). RBAC (viewer vs admin, Step G) is enforced
// per-RPC server-side before any handler body runs.
//
// EC4 is enforced by this file's own shape, not just by server-side
// checks: there is no RPC here that sets model_active directly, no
// "instant activate" verb, and no field on StartRollout/PromoteRollout
// that accepts a target stage or percentage. PromoteRollout advances
// EXACTLY one staged step (skipping only the current pause), the same
// single-step rule the automatic timer-driven advance uses internally —
// it cannot jump ahead. If a bypass verb isn't in this file, no caller,
// however privileged, can invoke one.
//
// createModelDraft (Phase-05.txt's own APIS CREATED wording) is
// deliberately NOT an RPC here: it never mutates anything (it reads the
// currently active manifest as the Model Studio editor's starting point),
// so it is the GraphQL query `modelDraft` instead — Phase-05.txt's own
// "createModelDraft/publishModelVersion -> control-plane
// RegisterModelManifest" line groups the two adjacent UX steps together,
// but only publish should ever produce a new signed version; a draft that
// silently persisted a manifest would defeat the whole point of staging
// an edit before committing it.
type AdminServiceServer interface {
	// -> control.v1.ControlService/RegisterModelManifest (unchanged, P04).
	// created_by is never a request field — derived server-side from the
	// authenticated caller (Step F), so a client can never attribute a
	// publish to someone else.
	PublishModelVersion(context.Context, *PublishModelVersionRequest) (*PublishModelVersionResponse, error)
	// -> control.v1.ControlService/CreateRollout (new this phase). Always
	// begins at the first staged step; there is no field to start
	// elsewhere or at a given percentage.
	StartRollout(context.Context, *StartRolloutRequest) (*StartRolloutResponse, error)
	// -> control.v1.ControlService/PromoteRollout. Manual "don't wait out
	// the pause" control (Architecture Part R: "live promote/rollback
	// controls") — advances exactly one step, identical in effect to the
	// automatic timer-driven advance, just human-triggered.
	PromoteRollout(context.Context, *PromoteRolloutRequest) (*PromoteRolloutResponse, error)
	// -> control.v1.ControlService/AbortRollout. Manual rollback — zeroes
	// canary traffic, identical in effect to an automatic AnalysisRun-
	// triggered rollback, just human-triggered.
	AbortRollout(context.Context, *AbortRolloutRequest) (*AbortRolloutResponse, error)
	// Local to admin-api's own api_keys grant (P01's table, reused) — does
	// not reach control-plane at all. raw_key is returned exactly once and
	// never persisted (mirrors data/seed/seed-test-tenant.sh's own
	// discipline); only its hash is stored.
	CreateApiKey(context.Context, *CreateApiKeyRequest) (*CreateApiKeyResponse, error)
	RevokeApiKey(context.Context, *RevokeApiKeyRequest) (*RevokeApiKeyResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) PublishModelVersion(context.Context, *PublishModelVersionRequest) (*PublishModelVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishModelVersion not implemented")
}
func (UnimplementedAdminServiceServer) StartRollout(context.Context, *StartRolloutRequest) (*StartRolloutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRollout not implemented")
}
func (UnimplementedAdminServiceServer) PromoteRollout(context.Context, *PromoteRolloutRequest) (*PromoteRolloutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PromoteRollout not implemented")
}
func (UnimplementedAdminServiceServer) AbortRollout(context.Context, *AbortRolloutRequest) (*AbortRolloutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortRollout not implemented")
}
func (UnimplementedAdminServiceServer) CreateApiKey(context.Context, *CreateApiKeyRequest) (*CreateApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateApiKey not implemented")
}
func (UnimplementedAdminServiceServer) RevokeApiKey(context.Context, *RevokeApiKeyRequest) (*RevokeApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeApiKey not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_PublishModelVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishModelVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).PublishModelVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_PublishModelVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).PublishModelVersion(ctx, req.(*PublishModelVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_StartRollout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRolloutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StartRollout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_StartRollout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StartRollout(ctx, req.(*StartRolloutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_PromoteRollout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteRolloutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).PromoteRollout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_PromoteRollout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).PromoteRollout(ctx, req.(*PromoteRolloutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AbortRollout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortRolloutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AbortRollout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_AbortRollout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AbortRollout(ctx, req.(*AbortRolloutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreateApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateApiKey(ctx, req.(*CreateApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RevokeApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RevokeApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RevokeApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RevokeApiKey(ctx, req.(*RevokeApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishModelVersion",
			Handler:    _AdminService_PublishModelVersion_Handler,
		},
		{
			MethodName: "StartRollout",
			Handler:    _AdminService_StartRollout_Handler,
		},
		{
			MethodName: "PromoteRollout",
			Handler:    _AdminService_PromoteRollout_Handler,
		},
		{
			MethodName: "AbortRollout",
			Handler:    _AdminService_AbortRollout_Handler,
		},
		{
			MethodName: "CreateApiKey",
			Handler:    _AdminService_CreateApiKey_Handler,
		},
		{
			MethodName: "RevokeApiKey",
			Handler:    _AdminService_RevokeApiKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/v1/admin.proto",
}
