// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: admin/v1/admin.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishModelVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelRef      string                 `protobuf:"bytes,1,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	SpecJson      string                 `protobuf:"bytes,2,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishModelVersionRequest) Reset() {
	*x = PublishModelVersionRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishModelVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishModelVersionRequest) ProtoMessage() {}

func (x *PublishModelVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishModelVersionRequest.ProtoReflect.Descriptor instead.
func (*PublishModelVersionRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *PublishModelVersionRequest) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

func (x *PublishModelVersionRequest) GetSpecJson() string {
	if x != nil {
		return x.SpecJson
	}
	return ""
}

type PublishModelVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionId     string                 `protobuf:"bytes,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishModelVersionResponse) Reset() {
	*x = PublishModelVersionResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishModelVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishModelVersionResponse) ProtoMessage() {}

func (x *PublishModelVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishModelVersionResponse.ProtoReflect.Descriptor instead.
func (*PublishModelVersionResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *PublishModelVersionResponse) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

// strategy_json describes the INTENDED step plan (e.g. staged percentages
// and pause durations) that control-plane uses to configure the
// underlying Argo Rollouts Rollout resource (Step M) — it configures how
// staging will proceed, it is not itself a live traffic-percent command.
type StartRolloutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelRef      string                 `protobuf:"bytes,1,opt,name=model_ref,json=modelRef,proto3" json:"model_ref,omitempty"`
	VersionId     string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	StrategyJson  string                 `protobuf:"bytes,3,opt,name=strategy_json,json=strategyJson,proto3" json:"strategy_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRolloutRequest) Reset() {
	*x = StartRolloutRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRolloutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRolloutRequest) ProtoMessage() {}

func (x *StartRolloutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRolloutRequest.ProtoReflect.Descriptor instead.
func (*StartRolloutRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *StartRolloutRequest) GetModelRef() string {
	if x != nil {
		return x.ModelRef
	}
	return ""
}

func (x *StartRolloutRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *StartRolloutRequest) GetStrategyJson() string {
	if x != nil {
		return x.StrategyJson
	}
	return ""
}

type StartRolloutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolloutId     string                 `protobuf:"bytes,1,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRolloutResponse) Reset() {
	*x = StartRolloutResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRolloutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRolloutResponse) ProtoMessage() {}

func (x *StartRolloutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRolloutResponse.ProtoReflect.Descriptor instead.
func (*StartRolloutResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *StartRolloutResponse) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

type PromoteRolloutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolloutId     string                 `protobuf:"bytes,1,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteRolloutRequest) Reset() {
	*x = PromoteRolloutRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteRolloutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteRolloutRequest) ProtoMessage() {}

func (x *PromoteRolloutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteRolloutRequest.ProtoReflect.Descriptor instead.
func (*PromoteRolloutRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *PromoteRolloutRequest) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

type PromoteRolloutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewStage      string                 `protobuf:"bytes,1,opt,name=new_stage,json=newStage,proto3" json:"new_stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteRolloutResponse) Reset() {
	*x = PromoteRolloutResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteRolloutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteRolloutResponse) ProtoMessage() {}

func (x *PromoteRolloutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteRolloutResponse.ProtoReflect.Descriptor instead.
func (*PromoteRolloutResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *PromoteRolloutResponse) GetNewStage() string {
	if x != nil {
		return x.NewStage
	}
	return ""
}

type AbortRolloutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolloutId     string                 `protobuf:"bytes,1,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRolloutRequest) Reset() {
	*x = AbortRolloutRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRolloutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRolloutRequest) ProtoMessage() {}

func (x *AbortRolloutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRolloutRequest.ProtoReflect.Descriptor instead.
func (*AbortRolloutRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *AbortRolloutRequest) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

type AbortRolloutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRolloutResponse) Reset() {
	*x = AbortRolloutResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRolloutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRolloutResponse) ProtoMessage() {}

func (x *AbortRolloutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRolloutResponse.ProtoReflect.Descriptor instead.
func (*AbortRolloutResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

type CreateApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Scopes        []string               `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiKeyRequest) Reset() {
	*x = CreateApiKeyRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiKeyRequest) ProtoMessage() {}

func (x *CreateApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *CreateApiKeyRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateApiKeyRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type CreateApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	RawKey        string                 `protobuf:"bytes,2,opt,name=raw_key,json=rawKey,proto3" json:"raw_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiKeyResponse) Reset() {
	*x = CreateApiKeyResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiKeyResponse) ProtoMessage() {}

func (x *CreateApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *CreateApiKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *CreateApiKeyResponse) GetRawKey() string {
	if x != nil {
		return x.RawKey
	}
	return ""
}

type RevokeApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeApiKeyRequest) Reset() {
	*x = RevokeApiKeyRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeApiKeyRequest) ProtoMessage() {}

func (x *RevokeApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeApiKeyRequest.ProtoReflect.Descriptor instead.
func (*RevokeApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeApiKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type RevokeApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeApiKeyResponse) Reset() {
	*x = RevokeApiKeyResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeApiKeyResponse) ProtoMessage() {}

func (x *RevokeApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeApiKeyResponse.ProtoReflect.Descriptor instead.
func (*RevokeApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

var File_admin_v1_admin_proto protoreflect.FileDescriptor

const file_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x14admin/v1/admin.proto\x12\badmin.v1\"V\n" +
	"\x1aPublishModelVersionRequest\x12\x1b\n" +
	"\tmodel_ref\x18\x01 \x01(\tR\bmodelRef\x12\x1b\n" +
	"\tspec_json\x18\x02 \x01(\tR\bspecJson\"<\n" +
	"\x1bPublishModelVersionResponse\x12\x1d\n" +
	"\n" +
	"version_id\x18\x01 \x01(\tR\tversionId\"v\n" +
	"\x13StartRolloutRequest\x12\x1b\n" +
	"\tmodel_ref\x18\x01 \x01(\tR\bmodelRef\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\x12#\n" +
	"\rstrategy_json\x18\x03 \x01(\tR\fstrategyJson\"5\n" +
	"\x14StartRolloutResponse\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x01 \x01(\tR\trolloutId\"6\n" +
	"\x15PromoteRolloutRequest\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x01 \x01(\tR\trolloutId\"5\n" +
	"\x16PromoteRolloutResponse\x12\x1b\n" +
	"\tnew_stage\x18\x01 \x01(\tR\bnewStage\"4\n" +
	"\x13AbortRolloutRequest\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x01 \x01(\tR\trolloutId\"\x16\n" +
	"\x14AbortRolloutResponse\"D\n" +
	"\x13CreateApiKeyRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x16\n" +
	"\x06scopes\x18\x02 \x03(\tR\x06scopes\"F\n" +
	"\x14CreateApiKeyResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x17\n" +
	"\araw_key\x18\x02 \x01(\tR\x06rawKey\",\n" +
	"\x13RevokeApiKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"\x16\n" +
	"\x14RevokeApiKeyResponse2\x83\x04\n" +
	"\fAdminService\x12b\n" +
	"\x13PublishModelVersion\x12$.admin.v1.PublishModelVersionRequest\x1a%.admin.v1.PublishModelVersionResponse\x12M\n" +
	"\fStartRollout\x12\x1d.admin.v1.StartRolloutRequest\x1a\x1e.admin.v1.StartRolloutResponse\x12S\n" +
	"\x0ePromoteRollout\x12\x1f.admin.v1.PromoteRolloutRequest\x1a .admin.v1.PromoteRolloutResponse\x12M\n" +
	"\fAbortRollout\x12\x1d.admin.v1.AbortRolloutRequest\x1a\x1e.admin.v1.AbortRolloutResponse\x12M\n" +
	"\fCreateApiKey\x12\x1d.admin.v1.CreateApiKeyRequest\x1a\x1e.admin.v1.CreateApiKeyResponse\x12M\n" +
	"\fRevokeApiKey\x12\x1d.admin.v1.RevokeApiKeyRequest\x1a\x1e.admin.v1.RevokeApiKeyResponseBJZHgithub.com/onezox/OneZox/services/admin-api/internal/pb/admin/v1;adminv1b\x06proto3"

var (
	file_admin_v1_admin_proto_rawDescOnce sync.Once
	file_admin_v1_admin_proto_rawDescData []byte
)

func file_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_admin_proto_rawDesc), len(file_admin_v1_admin_proto_rawDesc)))
	})
	return file_admin_v1_admin_proto_rawDescData
}

var file_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_admin_v1_admin_proto_goTypes = []any{
	(*PublishModelVersionRequest)(nil),  // 0: admin.v1.PublishModelVersionRequest
	(*PublishModelVersionResponse)(nil), // 1: admin.v1.PublishModelVersionResponse
	(*StartRolloutRequest)(nil),         // 2: admin.v1.StartRolloutRequest
	(*StartRolloutResponse)(nil),        // 3: admin.v1.StartRolloutResponse
	(*PromoteRolloutRequest)(nil),       // 4: admin.v1.PromoteRolloutRequest
	(*PromoteRolloutResponse)(nil),      // 5: admin.v1.PromoteRolloutResponse
	(*AbortRolloutRequest)(nil),         // 6: admin.v1.AbortRolloutRequest
	(*AbortRolloutResponse)(nil),        // 7: admin.v1.AbortRolloutResponse
	(*CreateApiKeyRequest)(nil),         // 8: admin.v1.CreateApiKeyRequest
	(*CreateApiKeyResponse)(nil),        // 9: admin.v1.CreateApiKeyResponse
	(*RevokeApiKeyRequest)(nil),         // 10: admin.v1.RevokeApiKeyRequest
	(*RevokeApiKeyResponse)(nil),        // 11: admin.v1.RevokeApiKeyResponse
}
var file_admin_v1_admin_proto_depIdxs = []int32{
	0,  // 0: admin.v1.AdminService.PublishModelVersion:input_type -> admin.v1.PublishModelVersionRequest
	2,  // 1: admin.v1.AdminService.StartRollout:input_type -> admin.v1.StartRolloutRequest
	4,  // 2: admin.v1.AdminService.PromoteRollout:input_type -> admin.v1.PromoteRolloutRequest
	6,  // 3: admin.v1.AdminService.AbortRollout:input_type -> admin.v1.AbortRolloutRequest
	8,  // 4: admin.v1.AdminService.CreateApiKey:input_type -> admin.v1.CreateApiKeyRequest
	10, // 5: admin.v1.AdminService.RevokeApiKey:input_type -> admin.v1.RevokeApiKeyRequest
	1,  // 6: admin.v1.AdminService.PublishModelVersion:output_type -> admin.v1.PublishModelVersionResponse
	3,  // 7: admin.v1.AdminService.StartRollout:output_type -> admin.v1.StartRolloutResponse
	5,  // 8: admin.v1.AdminService.PromoteRollout:output_type -> admin.v1.PromoteRolloutResponse
	7,  // 9: admin.v1.AdminService.AbortRollout:output_type -> admin.v1.AbortRolloutResponse
	9,  // 10: admin.v1.AdminService.CreateApiKey:output_type -> admin.v1.CreateApiKeyResponse
	11, // 11: admin.v1.AdminService.RevokeApiKey:output_type -> admin.v1.RevokeApiKeyResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_admin_v1_admin_proto_init() }
func file_admin_v1_admin_proto_init() {
	if File_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_admin_proto_rawDesc), len(file_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_admin_v1_admin_proto = out.File
	file_admin_v1_admin_proto_goTypes = nil
	file_admin_v1_admin_proto_depIdxs = nil
}
